name: Cypress Cloud

on:
  workflow_dispatch:
    inputs:
      spec:
        description: Run cypress command line
        default: cypress/e2e/*

jobs:
  cypress-e2e-electron:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6.0.2

      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: yarn install
          browser: electron
          record: true
          group: UI Electron
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: ad76e1ed-9db1-4cdd-8772-7dc497668a48
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        
        
